Er amends
NHS-Transformation-Unit/Lung_Health_Checks pull request #22
Opened 2024-06-20 14:10 UTC by elliotroyle

This PR covers all changes required for adding the M3 -> M24 follow up cohort across Y1, as specified in this [`issue`](https://github.com/NHS-Transformation-Unit/Lung_Health_Checks/issues/19).

I have done some minor spot checks and can see that the M24 input cohort has increased by approximately 6x. I will now begin to replicate these changes across the remaining years.

2024-06-21 09:51 UTC, ASW-Analyst requested changes
Please see the comments  for the amendments. Can I also just clarify that the other year `_6_m3_treat.R` and `_8_m12_treat.R` will also need to be amended for the new function definition.

2024-06-21 09:51 UTC, ASW-Analyst commented on data/config_inputs/lhc_config_inputs_v5.xlsx
Can you amend the fill of the cells in row 16 in the tab `m3_treat` so that they are not showing as user input values and consistent with other tabs.

2024-06-21 09:51 UTC, ASW-Analyst commented on data/config_inputs/lhc_config_inputs_v5.xlsx
Rows 6 and 7 need to be switched. The `m3_m24_fu_rate` occurs chronologically before the `m3_cancer_rate`

2024-06-21 09:51 UTC, ASW-Analyst commented on src/config/assumptions/assumptions_treatments_m3.R
Will need amending based on the switching of rows in the spreadsheet. Otherwise all fine.

2024-06-21 09:51 UTC, ASW-Analyst commented on src/model/y1/y1_8_m12_treat.R
> +y1_m24_FU_input_df <- bind_rows(y1_m3_m24_FU_input_df, y1_m24_FU_input_df)
The `bind_rows` call needs amending as the `y1_m24_FU_input_df` isn't defined. This will need amending to `y1_m12_m24_FU_input_df`

2024-06-21 10:40 UTC, elliotroyle commented on data/config_inputs/lhc_config_inputs_v5.xlsx
I think this might be rows 7 and 8. Please check if this is now showing correctly in the workbook.

2024-06-21 10:55 UTC, elliotroyle commented
All changes have been implemented and carried across to all appropriate Y2-5 scripts.

2024-06-21 14:22 UTC, ASW-Analyst requested changes
Please see additional amends to complete in #19 . The reviewed scripts are fine to be merged once those amendments are complete.

2024-06-24 21:46 UTC, ASW-Analyst approved these changes

2024-06-24 21:47 UTC, merged