Er amends
NHS-Transformation-Unit/Lung_Health_Checks pull request #23
Opened 2024-06-25 11:15 UTC by elliotroyle

PR initially for the first three actions within the #20 issue.

2024-06-25 12:59 UTC, ASW-Analyst requested changes
Please see the amendments for the `lhc_config_inputs_v5.xlsx` user input spreadsheet and the [`src/config/assumptions/assumptions_treatments_m3.R`](https://github.com/NHS-Transformation-Unit/Lung_Health_Checks/blob/78e1497535573fdea9a6b24dcd95e2ec4ff01df6/src/config/assumptions/assumptions_treatments_m3.R#L260)

2024-06-25 12:59 UTC, ASW-Analyst commented on data/config_inputs/lhc_config_inputs_v5.xlsx
Please can you remove the cell protection for cells `E22:I22` in each of the four `_incidental` tabs.

2024-06-25 12:59 UTC, ASW-Analyst commented on src/config/assumptions/assumptions_treatments_m3.R
Defining the `m3_inc_tub_yX` assumptions, TB rates, has been removed from the code but needs adding in.

2024-06-25 15:13 UTC, ASW-Analyst reviewed
Amends to `lhc_config_inputs_v5.xlsx` and `src/config/assumptions/assumptions_treatments_m3.R` approved

2024-06-25 16:32 UTC, elliotroyle commented
Added a package to the requirements (`stringr`) and adapted the `initial_treatment.R` function script and `y1_4_init_treatment.R` model script to adapt method for calculating incidentals. Will replicate this methodology for other Y1 scripts (M3, M12 and M24) before applying to Y2-5.

2024-06-26 14:51 UTC, ASW-Analyst reviewed
Amendments look good, please add in for the other periods and each model year.

2024-06-26 17:05 UTC, elliotroyle commented
All changes made to replicate Y1 initial incidental methodology across M3, M12 and M24 in Y1 as well as all scripts in Y2-5.

2024-06-27 15:35 UTC, ASW-Analyst approved these changes
Amendments approved

2024-06-27 15:36 UTC, merged